backend:
  name: github
  repo: penguibird/kousekPoKousku
  branch: master
  site_domain: cms.netlify.com


media_folder: static/img
public_folder: /img

collections:
  - name: 'aktuality'
    label: 'Aktuality'
    folder: 'content/aktuality'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    preview: false
    identifier_field: name,
    fields:
    - { label: "ID", name: "id", widget: "id"}
    - { label: "Nazev", name: 'name', widget: 'string'}
    - {label: 'Text', name: 'body', widget: 'markdown'}
    - label: 'Obrazek'
      name: 'image'
      widget: 'object'
      collapsed: true
      fields:
      - {label: 'Obrazek', name: 'image', widget: 'image'}
      - {label: 'Popis obrazku', name: 'imageAlt', widget: 'string'}
  - name: 'projekty'
    label: 'Projekty'
    folder: 'content/projekty'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    preview: false
    identifier_field: name,
    fields:
      - { label: "ID", name: "id", widget: "id"}
      - { label: 'Nazev', name: 'name', widget: 'string' }
      - { label: 'Cena', name: 'price', widget: 'number' }
      - { label: 'Rok', name: 'year', widget: 'number', value_type: 'int', min: 2000, max: 2100, step: 1, default: '', format: 'YYYY' }
      - { label: 'Popis', name: 'description', widget: 'markdown' }
      - label: 'Obrazek'
        name: 'image'
        widget: 'object'
        collapsed: false
        fields:
        - {label: 'Obrazek', name: 'image', widget: 'image'}
        - {label: 'Popis obrazku', name: 'imageAlt', widget: 'string'}
      - {label: 'Podporen z kouskovani?', name: 'kouskovani', widget: 'boolean'}
      - {label: 'Nazev mista', name: 'locationName', widget: 'string'}
      - label: 'GPS souradnice'
        name: 'position' 
        widget: 'object'
        collapsed: false
        fields: 
        - {label: 'Lat', name: 'lat', widget: 'number', value_type: 'float'}
        - {label: 'Lng', name: 'lng', widget: 'number', value_type: 'float'}
