name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install nod
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install

      - name: build
        run: npm run build
        env:
          GATSBY_ENV: "prod"
          
      - name: upload-artifact
        uses: actions/upload-artifact@v2
        with:
         name: public-folder
         path: public
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: download-artifact
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: public
      - name: Setup Ruby, JRuby and TruffleRuby
        uses: ruby/setup-ruby@v1.78.0
        with: 
          ruby-version: 2.6
        
      - name: Checkout
        uses: actions/checkout@master
#       - name: Install
#         run: bundle install
      - name: Percy Test
        run: npx percy snapshot public/
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

  deploy:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:    
      - name: download-artifact
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: public
          
      - name: deploy
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ftp.jules.tojeono.cz
          username: kousekpokousku.cz
          password: ${{ secrets.ftp_password }}
          local-dir: ./public/
          server-dir: ./public_html/www/
          dangerous-clean-slate: true
